version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    volumes:
      - ./envs:/opt/app/envs
      - ./uploads:/opt/app/uploads
    container_name: content-service-api
    ports:
      - 3002:3000
  rmq:
    image: rabbitmq:3-management
    container_name: content-service-rmq-management
    restart: always
    ports:
      - '5673:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    extends:
      file: docker-compose.dev.yml
      service: rmq
  converter:
    build:
      context: .
      dockerfile: ./apps/converter/Dockerfile
    restart: always
    container_name: content-service-converter
    volumes:
      - ./envs:/opt/app/envs
    depends_on:
      - rmq
